/// Golden Rules enforcement tests — generated by spine-rules.
use spine_rules::golden_rules_suite;

golden_rules_suite! {
    binary: env!("CARGO_BIN_EXE_lock"),
    operator_json: include_str!("../operator.json"),
    source_files: &[
        "src/lib.rs",
        "src/refusal/mod.rs",
        "src/lockfile/mod.rs",
        "src/verify/mod.rs",
        "src/verify/output.rs",
        "src/output/mod.rs",
    ],
}
